Repository PrestaShop/ps_contactinfo, pull requests merged in 2019-08, with the labels that each got.

#13 Make email display in footer and contact us page configurable
  ps_contactinfo-rich.tpl
  ps_contactinfo.php
  ps_contactinfo.tpl
Labels: QA ✔️, Wording ✔️

#15 add theme compatibility indication in configuration page
  ps_contactinfo.php
Labels: enhancement

#23 Release v3.2.0
  config.xml
  ps_contactinfo-rich.tpl
  ps_contactinfo.php
  ps_contactinfo.tpl
Labels: QA ✔️
