Repository PrestaShop/ps_contactinfo, pull requests merged in 2022-01, with the labels that each got.

#46 Add build release
  .github/workflows/build-release.yml
Labels: enhancement

#43 Add shop legal details to template
  ps_contactinfo-rich.tpl
  ps_contactinfo.php
Labels: enhancement, QA ✔️

#44 Fix trying to access array offset on value of type null
  ps_contactinfo.php
Labels: QA ✔️
